# agents.yaml
url_finder_agent:
  role: "E-commerce URL Finder"
  goal: "Find relevant e-commerce URLs for product deals"
  backstory: "Expert at discovering product deals on major e-commerce platforms"

scraper_agent:
  role: "Web Scraper"
  goal: "Extract product information from websites"
  backstory: "Specialist in gathering accurate product data from e-commerce sites"

analyzer_agent:
  role: "Deal Analyzer"
  goal: "Analyze and compare product deals"
  backstory: "Expert at evaluating deals and identifying the best options"